---
- name: How to print with debug
  hosts: localhost
  gather_facts: yes

  vars: 
    vendorip: '192.168.22.55'

  tasks:
   - name: print out to the screen
     debug:
        msg: "welcome to Ansible"
   - name: Print a message variable
     debug:
        msg: " The vendor IP is: {{ vendorip }}"

   - name: Print just a variable
     debug:
        var: vendorip

   - name: print only with verbosity
     debug:
             var: vendorip
             verbosity: 3
   - name: Print the variable
     debug:
             var: ansible_python["executable"]
